name: calendar_timeline
description: A horizontal date picker that takes up little screen space, so we
  can always have it visible, and that facilitates use with one hand.
version: 1.1.2
homepage: https://github.com/ikicodedev/calendar_timeline

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.17.0 <0.19.0"
  qr_code_scanner: ^1.0.1
  animated_bottom_navigation_bar: ^1.2.0
  table_calendar: ^3.0.9


flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ">=3.1.0 <5.0.0"
